import type {Metadata} from "next";
import "./globals.css";
import {GlobalProvider} from "./globalProvider";

export const metadata: Metadata = {
  title: "Baptizo - Audio books, Audio series, Audio dramas streaming app",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang='en' suppressHydrationWarning>
      <body className={`!font-aileron antialiased bg-background`}>
        <GlobalProvider>{children}</GlobalProvider>
      </body>
    </html>
  );
}
